# Generated by Django 5.0.3 on 2024-03-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_pet_age_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption_status',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.user'),
        ),
        migrations.AlterField(
            model_name='adoption_status',
            name='adoption_date',
            field=models.DateField(blank=True, max_length=20),
        ),
    ]
