# Generated by Django 5.0.3 on 2024-03-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_adoption_status_adopted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption_status',
            name='adoption_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
