# Generated by Django 5.0.3 on 2024-03-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_adoption_status_adoption_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history_for_the_pet', models.CharField(max_length=350)),
                ('cuurent_health_status', models.CharField(max_length=350)),
                ('vaccinations', models.CharField(max_length=75)),
                ('on_going_medication', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('free_hours_a_week', models.IntegerField()),
                ('exprtise', models.TextField(max_length=750)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='health_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playground.medical_history'),
        ),
    ]
