# Generated by Django 5.0.3 on 2024-03-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_medical_history_volunteer_pet_health_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_history',
            old_name='cuurent_health_status',
            new_name='current_health_status',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='health_status',
        ),
    ]
